apiVersion: apps/v1
kind: Deployment
metadata:
  name: raft-node
spec:
  replicas: 3
  selector:
    matchLabels:
      app: raft-node
  template:
    metadata:
      labels:
        app: raft-node
    spec:
      containers:
      - name: raft-node
        image: localhost:5001/raft-node:1.0 
        command: ["./raft-node"]
        args: ["node1", "127.0.0.1", "5002"]
        # args: ["node1, node2, node3"]
        ports:
        - containerPort: 8080
        resources:
          limits:
            cpu: "1"
            memory: 1Gi
          requests:
            cpu: 500m
            memory: 1Gi
