---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - replicaset.vanderbilt.edu
  resources:
  - raftreplicasetvandies
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - replicaset.vanderbilt.edu
  resources:
  - raftreplicasetvandies/finalizers
  verbs:
  - update
- apiGroups:
  - replicaset.vanderbilt.edu
  resources:
  - raftreplicasetvandies/status
  verbs:
  - get
  - patch
  - update
