apiVersion: v1
kind: Service
metadata:
  name: redis-test-master
  labels:
    app: redis
spec:
  type: NodePort
  ports:
  - name: redis
    port: 6379
    targetPort: 6379
  selector:
    app: redis
    role: master